### ISSUE TITLE
It still crashes

### ISSUE THREAD

**Issue by dkrmdi** [inthecatsdreams/vita-volume#2]
![DSC_0057](https://user-images.githubusercontent.com/53800025/63555542-51db0400-c50f-11e9-8f54-de33bb47846a.JPG)

**Comment by inthecatsdreams** [comment]
Well there is nothing I can do. I tried it on multiple vitas on different firmwares and the app doesn't crash, never crashed, not even once. So that's a problem on your end. 

Try to download the latest version again and completely remove the previous one.

https://github.com/inthecatsdreams/vita-volume/releases/download/1.2-1/VitaVolume.vpk
